# Generated by Django 5.0.1 on 2024-01-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category_product_description_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
