# Generated by Django 5.0.1 on 2024-02-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
